/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p2ex1_gabrielzelaya;

import java.util.ArrayList;
import thispc.Laptop;
import thispc.PC;
import thispc.PC_Escritorio;

/**
 *
 * @author gabri
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CRUD = new javax.swing.JFrame();
        JTP_crud = new javax.swing.JTabbedPane();
        JP_crear = new javax.swing.JPanel();
        Btn_PC = new javax.swing.JButton();
        btn_Laptop = new javax.swing.JButton();
        JP_listar = new javax.swing.JPanel();
        JP_eliminar = new javax.swing.JPanel();
        JF_crearPC = new javax.swing.JFrame();
        bg_crearPC = new javax.swing.JPanel();
        JL_ip = new javax.swing.JLabel();
        JTF_ip = new javax.swing.JTextField();
        JL_Mask = new javax.swing.JLabel();
        JTF_mask = new javax.swing.JTextField();
        JL_tarjetag = new javax.swing.JLabel();
        JL_hostname1 = new javax.swing.JLabel();
        JTF_hostname1 = new javax.swing.JTextField();
        JL_RAM1 = new javax.swing.JLabel();
        JTF_RAM1 = new javax.swing.JTextField();
        JL_storage1 = new javax.swing.JLabel();
        JTF_storage1 = new javax.swing.JTextField();
        btn_sdd = new javax.swing.JRadioButton();
        btn_hdd = new javax.swing.JRadioButton();
        JL_type1 = new javax.swing.JLabel();
        cb_tarjetag = new javax.swing.JCheckBox();
        btn_agregarPC = new javax.swing.JButton();
        storageType = new javax.swing.ButtonGroup();
        JF_crearLaptop = new javax.swing.JFrame();
        bg_laptop = new javax.swing.JPanel();
        JL_ip2 = new javax.swing.JLabel();
        JTF_ip2 = new javax.swing.JTextField();
        JL_Mask2 = new javax.swing.JLabel();
        JTF_mask2 = new javax.swing.JTextField();
        JL_RGB = new javax.swing.JLabel();
        JL_hostname2 = new javax.swing.JLabel();
        JTF_hostname2 = new javax.swing.JTextField();
        JL_marca = new javax.swing.JLabel();
        JTF_marca = new javax.swing.JTextField();
        JL_pantalla = new javax.swing.JLabel();
        JTF_pantalla = new javax.swing.JTextField();
        cb_RGB = new javax.swing.JCheckBox();
        btn_agregarPC1 = new javax.swing.JButton();
        bg_principal = new javax.swing.JPanel();
        btn_ingresar = new javax.swing.JButton();
        btn_crud = new javax.swing.JButton();

        CRUD.setMinimumSize(new java.awt.Dimension(846, 486));
        CRUD.setResizable(false);

        JP_crear.setBackground(new java.awt.Color(102, 102, 255));
        JP_crear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_PC.setText("PC");
        Btn_PC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_PCMouseClicked(evt);
            }
        });
        JP_crear.add(Btn_PC, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 100, 50));

        btn_Laptop.setText("LAPTOP");
        btn_Laptop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LaptopMouseClicked(evt);
            }
        });
        btn_Laptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LaptopActionPerformed(evt);
            }
        });
        JP_crear.add(btn_Laptop, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 90, 50));

        JTP_crud.addTab("Crear", JP_crear);

        javax.swing.GroupLayout JP_listarLayout = new javax.swing.GroupLayout(JP_listar);
        JP_listar.setLayout(JP_listarLayout);
        JP_listarLayout.setHorizontalGroup(
            JP_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        JP_listarLayout.setVerticalGroup(
            JP_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        JTP_crud.addTab("Listar", JP_listar);

        javax.swing.GroupLayout JP_eliminarLayout = new javax.swing.GroupLayout(JP_eliminar);
        JP_eliminar.setLayout(JP_eliminarLayout);
        JP_eliminarLayout.setHorizontalGroup(
            JP_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );
        JP_eliminarLayout.setVerticalGroup(
            JP_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        JTP_crud.addTab("Eliminar", JP_eliminar);

        javax.swing.GroupLayout CRUDLayout = new javax.swing.GroupLayout(CRUD.getContentPane());
        CRUD.getContentPane().setLayout(CRUDLayout);
        CRUDLayout.setHorizontalGroup(
            CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JTP_crud, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        CRUDLayout.setVerticalGroup(
            CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTP_crud)
                .addGap(18, 18, 18))
        );

        JF_crearPC.setBackground(new java.awt.Color(102, 102, 255));
        JF_crearPC.setResizable(false);
        JF_crearPC.setSize(new java.awt.Dimension(645, 470));

        bg_crearPC.setBackground(new java.awt.Color(102, 102, 255));
        bg_crearPC.setMinimumSize(new java.awt.Dimension(430, 221));
        bg_crearPC.setPreferredSize(new java.awt.Dimension(645, 470));
        bg_crearPC.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL_ip.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JL_ip.setText("IP Adress:");
        bg_crearPC.add(JL_ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 30));

        JTF_ip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_ipActionPerformed(evt);
            }
        });
        bg_crearPC.add(JTF_ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 200, 30));

        JL_Mask.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JL_Mask.setText("Mask:");
        bg_crearPC.add(JL_Mask, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 30));
        bg_crearPC.add(JTF_mask, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 200, 30));

        JL_tarjetag.setText("Tarjeta Gráfica: ");
        bg_crearPC.add(JL_tarjetag, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, 30));

        JL_hostname1.setText("Hostname:");
        bg_crearPC.add(JL_hostname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, 30));
        bg_crearPC.add(JTF_hostname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 200, 30));

        JL_RAM1.setText("RAM:");
        bg_crearPC.add(JL_RAM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, 30));
        bg_crearPC.add(JTF_RAM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 200, 30));

        JL_storage1.setText("Storage:");
        bg_crearPC.add(JL_storage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 60, 30));
        bg_crearPC.add(JTF_storage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 200, 30));

        storageType.add(btn_sdd);
        btn_sdd.setText("SDD");
        bg_crearPC.add(btn_sdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        storageType.add(btn_hdd);
        btn_hdd.setText("HDD");
        bg_crearPC.add(btn_hdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        JL_type1.setText("Storage Type:");
        bg_crearPC.add(JL_type1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 80, 30));
        bg_crearPC.add(cb_tarjetag, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, -1, -1));

        btn_agregarPC.setText("Agregar");
        btn_agregarPC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarPCMouseClicked(evt);
            }
        });
        bg_crearPC.add(btn_agregarPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        javax.swing.GroupLayout JF_crearPCLayout = new javax.swing.GroupLayout(JF_crearPC.getContentPane());
        JF_crearPC.getContentPane().setLayout(JF_crearPCLayout);
        JF_crearPCLayout.setHorizontalGroup(
            JF_crearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_crearPCLayout.createSequentialGroup()
                .addComponent(bg_crearPC, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addContainerGap())
        );
        JF_crearPCLayout.setVerticalGroup(
            JF_crearPCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_crearPCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg_crearPC, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );

        JF_crearLaptop.setBackground(new java.awt.Color(102, 102, 255));
        JF_crearLaptop.setSize(new java.awt.Dimension(636, 463));

        bg_laptop.setBackground(new java.awt.Color(102, 102, 255));
        bg_laptop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JL_ip2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JL_ip2.setText("IP Adress:");
        bg_laptop.add(JL_ip2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 60, 30));

        JTF_ip2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_ip2ActionPerformed(evt);
            }
        });
        bg_laptop.add(JTF_ip2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 200, 30));

        JL_Mask2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JL_Mask2.setText("Mask:");
        bg_laptop.add(JL_Mask2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, 30));
        bg_laptop.add(JTF_mask2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 200, 30));

        JL_RGB.setText("RGB:");
        bg_laptop.add(JL_RGB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 50, 30));

        JL_hostname2.setText("Hostname:");
        bg_laptop.add(JL_hostname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 60, 30));
        bg_laptop.add(JTF_hostname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 200, 30));

        JL_marca.setText("Marca:");
        bg_laptop.add(JL_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, 30));
        bg_laptop.add(JTF_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 200, 30));

        JL_pantalla.setText("Pantalla:");
        bg_laptop.add(JL_pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 60, 30));
        bg_laptop.add(JTF_pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 200, 30));
        bg_laptop.add(cb_RGB, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        btn_agregarPC1.setText("Agregar");
        btn_agregarPC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_agregarPC1MouseClicked(evt);
            }
        });
        bg_laptop.add(btn_agregarPC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        javax.swing.GroupLayout JF_crearLaptopLayout = new javax.swing.GroupLayout(JF_crearLaptop.getContentPane());
        JF_crearLaptop.getContentPane().setLayout(JF_crearLaptopLayout);
        JF_crearLaptopLayout.setHorizontalGroup(
            JF_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_crearLaptopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg_laptop, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                .addContainerGap())
        );
        JF_crearLaptopLayout.setVerticalGroup(
            JF_crearLaptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JF_crearLaptopLayout.createSequentialGroup()
                .addComponent(bg_laptop, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        bg_principal.setBackground(new java.awt.Color(102, 102, 255));
        bg_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ingresar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        bg_principal.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 230, 169, 67));

        btn_crud.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btn_crud.setText("CRUD");
        btn_crud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_crudMouseClicked(evt);
            }
        });
        btn_crud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crudActionPerformed(evt);
            }
        });
        bg_principal.add(btn_crud, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 119, 169, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bg_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_crudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_crudMouseClicked
        this.setVisible(false);
        CRUD.setLocationRelativeTo(this);
        CRUD.setVisible(true);
    }//GEN-LAST:event_btn_crudMouseClicked

    private void btn_crudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_crudActionPerformed

    private void Btn_PCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_PCMouseClicked
        CRUD.setVisible(false);
        JF_crearPC.setLocationRelativeTo(this);
        JF_crearPC.setVisible(true);
    }//GEN-LAST:event_Btn_PCMouseClicked

    private void JTF_ipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_ipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_ipActionPerformed

    private void btn_agregarPCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarPCMouseClicked
        String tipo;
        if(btn_hdd.isSelected()){
            tipo = "HDD";
        }else{
            tipo = "SDD";
        }
        boolean flag = false;
        if(cb_tarjetag.isSelected()){
            flag = true;
        }
        PC_Escritorio pc = new PC_Escritorio(
                Integer.parseInt(JTF_RAM1.getText()),
                Integer.parseInt(JTF_storage1.getText()),
                tipo,
                flag,
                JTF_ip.getText(),
                JTF_mask.getText(),
                JTF_hostname1.getText()
        );
        pcs.add(pc);
    }//GEN-LAST:event_btn_agregarPCMouseClicked

    private void btn_LaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LaptopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LaptopActionPerformed

    private void btn_LaptopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LaptopMouseClicked
       CRUD.setVisible(false);
        JF_crearLaptop.setLocationRelativeTo(this);
        JF_crearLaptop.setVisible(true);
    }//GEN-LAST:event_btn_LaptopMouseClicked

    private void JTF_ip2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_ip2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_ip2ActionPerformed

    private void btn_agregarPC1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregarPC1MouseClicked
        boolean flag = false;
        if(cb_RGB.isSelected()){
            flag = true;
        }
        Laptop lp = new Laptop(JTF_marca.getText(),
                JTF_pantalla.getText(), 
                flag, 
                JTF_ip2.getText(),
                JTF_mask2.getText(), 
                JTF_hostname2.getText()
        );
        pcs.add(lp);
    }//GEN-LAST:event_btn_agregarPC1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_PC;
    private javax.swing.JFrame CRUD;
    private javax.swing.JFrame JF_crearLaptop;
    private javax.swing.JFrame JF_crearPC;
    private javax.swing.JLabel JL_Mask;
    private javax.swing.JLabel JL_Mask2;
    private javax.swing.JLabel JL_RAM1;
    private javax.swing.JLabel JL_RGB;
    private javax.swing.JLabel JL_hostname1;
    private javax.swing.JLabel JL_hostname2;
    private javax.swing.JLabel JL_ip;
    private javax.swing.JLabel JL_ip2;
    private javax.swing.JLabel JL_marca;
    private javax.swing.JLabel JL_pantalla;
    private javax.swing.JLabel JL_storage1;
    private javax.swing.JLabel JL_tarjetag;
    private javax.swing.JLabel JL_type1;
    private javax.swing.JPanel JP_crear;
    private javax.swing.JPanel JP_eliminar;
    private javax.swing.JPanel JP_listar;
    private javax.swing.JTextField JTF_RAM1;
    private javax.swing.JTextField JTF_hostname1;
    private javax.swing.JTextField JTF_hostname2;
    private javax.swing.JTextField JTF_ip;
    private javax.swing.JTextField JTF_ip2;
    private javax.swing.JTextField JTF_marca;
    private javax.swing.JTextField JTF_mask;
    private javax.swing.JTextField JTF_mask2;
    private javax.swing.JTextField JTF_pantalla;
    private javax.swing.JTextField JTF_storage1;
    private javax.swing.JTabbedPane JTP_crud;
    private javax.swing.JPanel bg_crearPC;
    private javax.swing.JPanel bg_laptop;
    private javax.swing.JPanel bg_principal;
    private javax.swing.JButton btn_Laptop;
    private javax.swing.JButton btn_agregarPC;
    private javax.swing.JButton btn_agregarPC1;
    private javax.swing.JButton btn_crud;
    private javax.swing.JRadioButton btn_hdd;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JRadioButton btn_sdd;
    private javax.swing.JCheckBox cb_RGB;
    private javax.swing.JCheckBox cb_tarjetag;
    private javax.swing.ButtonGroup storageType;
    // End of variables declaration//GEN-END:variables

    ArrayList<PC> pcs = new ArrayList<>();
}
